# Generated by Django 4.2.24 on 2025-09-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Fan',
            },
        ),
    ]
