# Generated by Django 4.2.24 on 2025-10-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(verbose_name='Savol matni')),
            ],
        ),
        migrations.CreateModel(
            name='Javob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=255, verbose_name='Javob matni')),
                ('togri', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javoblar', to='baza.savol')),
            ],
        ),
    ]
