# Generated by Django 4.2.24 on 2025-10-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_savol_javob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FISh', models.CharField(max_length=100)),
                ('seriya', models.CharField(max_length=100)),
                ('raqami', models.IntegerField(default=0)),
                ('sinf', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
    ]
