# Generated by Django 4.2.24 on 2025-10-15 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sinf',
            },
        ),
        migrations.AddField(
            model_name='savol',
            name='fan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='baza.fan'),
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('javob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.javob')),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.savol')),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.sinf')),
            ],
        ),
        migrations.AddField(
            model_name='savol',
            name='sinf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='baza.sinf'),
        ),
    ]
