# Generated by Django 4.2.24 on 2025-10-15 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0004_sinf_savol_fan_userresponse_savol_sinf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='sinf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baza.sinf'),
        ),
    ]
