# Generated by Django 4.2.24 on 2025-10-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0005_fan_sinf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='sinf',
        ),
        migrations.AddField(
            model_name='sinf',
            name='fan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baza.fan'),
        ),
    ]
