# Generated by Django 4.2.24 on 2025-10-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0006_remove_fan_sinf_sinf_fan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinf',
            name='fan',
        ),
        migrations.AddField(
            model_name='fan',
            name='sinf',
            field=models.ManyToManyField(blank=True, null=True, related_name='sinflar', to='baza.sinf'),
        ),
    ]
