# Generated by Django 4.2.24 on 2025-10-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0007_remove_sinf_fan_fan_sinf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='javob',
        ),
        migrations.AddField(
            model_name='savol',
            name='javob',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Javob matni'),
        ),
        migrations.AddField(
            model_name='savol',
            name='togri',
            field=models.BooleanField(default=True, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='fan',
            name='sinf',
            field=models.ManyToManyField(related_name='sinflar', to='baza.sinf'),
        ),
        migrations.DeleteModel(
            name='Javob',
        ),
    ]
