# Generated by Django 4.2.24 on 2025-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0009_remove_savol_javob_remove_savol_togri_javob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='javob',
        ),
        migrations.AddField(
            model_name='savol',
            name='variantlar',
            field=models.JSONField(blank=True, null=True, verbose_name='Variantlar'),
        ),
        migrations.DeleteModel(
            name='Javob',
        ),
    ]
