# Generated by Django 4.2.24 on 2025-10-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0011_remove_savol_variantlar_javob_userresponse_javob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savol',
            options={'verbose_name_plural': 'Savol'},
        ),
    ]
