# Generated by Django 4.2.24 on 2025-10-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0012_alter_savol_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='jins',
            field=models.CharField(choices=[('male', "O'g'il bola"), ('female', 'Qiz bola')], default='male', max_length=10),
        ),
    ]
