# Generated by Django 4.2.24 on 2025-10-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0013_student_jins'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='imported',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
