# Generated by Django 4.2.24 on 2025-10-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0014_student_created_at_student_imported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='imported',
        ),
    ]
