# Generated by Django 4.2.24 on 2025-10-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0015_remove_student_created_at_remove_student_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
