# Generated by Django 4.2.24 on 2025-10-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0016_student_imported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='imported',
        ),
    ]
