# Generated by Django 4.2.24 on 2025-10-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0019_alter_student_jins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='jins',
            field=models.CharField(choices=[("o'g'il bola", "o'g'il bola"), ('qiz bola', 'qiz bola')], default='qiz bola', max_length=100),
        ),
    ]
